#!/bin/bash -e
# $File: gendoc
# $Date: Fri Jul 13 10:39:41 2012 +0800
# $Author: jiakai <jia.kai66@gmail.com>

. ../init.sh
# make clean
export PYTHONDONTWRITEBYTECODE=1
rm -f source/autogen/ftp9.rst

sphinx-apidoc -o source/autogen ../src/
rm -f source/autogen/modules.rst

make html

# vim: ft=sh
