#!/bin/bash -e
# $File: gendoc
# $Date: Sun Aug 12 22:02:06 2012 +0800
# $Author: jiakai <jia.kai66@gmail.com>

. ../init.sh
# make clean
export PYTHONDONTWRITEBYTECODE=1
rm -f source/autogen/ftp9.rst

sphinx-apidoc -o source/autogen ../src/
rm -f source/autogen/modules.rst

make html

rm -f build/html/_modules/ftp9/config_overwrite.html

# vim: ft=sh
